//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Testova
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказание услуг.
    /// </summary>
    // *** Start programmer edit section *** (ОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (ОказаниеУслуг CustomAttributes)
    [AutoAltered()]
    [Caption("Оказание услуг")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказаниеУслугE", new string[] {
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "Услуга as \'Услуга\'",
            "Услуга.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Сотрудник.Фамилия",
            "Услуга.Наименование"})]
    [MasterViewDefineAttribute("ОказаниеУслугE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ОказаниеУслугE", "Услуга", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ОказаниеУслуг : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Testova.Сотрудник fСотрудник;
        
        private IIS.Testova.Услуга fУслуга;
        
        private IIS.Testova.Запись fЗапись;
        
        // *** Start programmer edit section *** (ОказаниеУслуг CustomMembers)

        // *** End programmer edit section *** (ОказаниеУслуг CustomMembers)

        
        /// <summary>
        /// Оказание услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Testova.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Сотрудник Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Сотрудник Get start)
                IIS.Testova.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ОказаниеУслуг.Сотрудник Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Сотрудник Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Сотрудник Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// Оказание услуг.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Услуга CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Testova.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Get start)
                IIS.Testova.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Услуга Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Testova.Запись.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеУслуг.Запись CustomAttributes)

        // *** End programmer edit section *** (ОказаниеУслуг.Запись CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Запись"})]
        public virtual IIS.Testova.Запись Запись
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Get start)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Get start)
                IIS.Testova.Запись result = this.fЗапись;
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Get end)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Set start)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Set start)
                this.fЗапись = value;
                // *** Start programmer edit section *** (ОказаниеУслуг.Запись Set end)

                // *** End programmer edit section *** (ОказаниеУслуг.Запись Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказаниеУслугE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеУслугE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеУслугE", typeof(IIS.Testova.ОказаниеУслуг));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ОказаниеУслуг.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfОказаниеУслуг CustomAttributes)
    public class DetailArrayOfОказаниеУслуг : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Testova.DetailArrayOfОказаниеУслуг members)

        // *** End programmer edit section *** (IIS.Testova.DetailArrayOfОказаниеУслуг members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ОказаниеУслуг by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ОказаниеУслуг.
        /// </summary>
        public DetailArrayOfОказаниеУслуг(IIS.Testova.Запись fЗапись) : 
                base(typeof(ОказаниеУслуг), ((ICSSoft.STORMNET.DataObject)(fЗапись)))
        {
        }
        
        public IIS.Testova.ОказаниеУслуг this[int index]
        {
            get
            {
                return ((IIS.Testova.ОказаниеУслуг)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Testova.ОказаниеУслуг dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
